- hosts: localhost
  vars:
    homedir: "{{lookup('env', 'HOME')}}"
  tasks:
    - name: Copy dotfiles and dirs
      copy: src="{{playbook_dir}}/home/{{item}}" dest="{{homedir}}/{{item}}"
      with_items:
        [".config/", ".gdbinit", ".gitconfig", ".mybin/", ".vim/", ".vimrc", ".pythonrc"]

    - name: Add contents of .profile to ~/.bashrc (linux)
      blockinfile:
        dest: "{{homedir}}/.bashrc"
        block: "{{ lookup('file', 'home/.profile') }}"
      when: ansible_os_family == 'Debian' or ansible_distribution == 'Archlinux'
