- hosts: localhost
  vars:
    homedir: "{{lookup('env', 'HOME')}}"
  tasks:
    - name: Copy dotfiles and dirs
      copy: src="{{playbook_dir}}/{{item}}" dest="{{homedir}}/{{item}}"
      with_items:
        [".vim/", ".mybin/", ".vimrc", ".gitconfig"]

    - name: Ubuntu | Add contents of .profile to ~/.bashrc
      blockinfile:
        dest: "{{homedir}}/.bashrc"
        block: "{{ lookup('file', '.profile') }}"
      when: ansible_distribution == 'Ubuntu'
